### ISSUE TITLE
Clean up the root directory of the project

### ISSUE THREAD

**Issue by dstengle** [kenzanlabs/ami-roles#10]
The files for each profile should not be kept in the root of the project. They should be moved to something like /ami-profiles.

Also, these files are *extremely* repetitive. 99% of these are templated based on the role name. There could easily be a driver script that copies the template, fills in the values (or does some ansible command line magic?) and runs ansible from there.

@dpeterka @rohitagarwal01 ^^

**Comment by dpeterka** [comment]
@dstengle please close this issue
